#Tabla de multiplicar

print("tabla del 1")
tablaM(1)
print("tabla del 2")
tablaM(2)
print("tabla del 3")
tablaM(3)
print("tabla del 4")
tablaM(4)
print("tabla del 5")
tablaM(5)
print("tabla del 6")
tablaM(6)
print("tabla del 7")
tablaM(7)
print("tabla del 8")
tablaM(8)
print("tabla del 9")
tablaM(9)
print("tabla del 10")
tablaM(10)
print("Fin")
